### ISSUE TITLE
Quiz Aufgabenstellung

### ISSUE THREAD

**Issue by MatrixCode84** [JirkaDellOro/Softwaredesign#22]
"Je nach Frage kann die Anzahl der Antwortoptionen variieren"

Wie ist das gemeint?

**Comment by JirkaDellOro** [comment]
Das meint das gleiche wie die "2 bis 6 Antwortmöglichkeiten". Verschiedene Fragen bringen verschiedene Anzahlen an Antwortoptionen mit sich.
