### ISSUE TITLE
Steckbrief

### ISSUE THREAD

**Issue by JirkaDellOro** [JirkaDellOro/Softwaredesign#25]

**Comment by Bassadin** [comment]
Hallo @JirkaDellOro :) Repo ist erstellt und [GitHub Pages aktiviert](https://vads.github.io/MIB4-Softwaredesign/steckbrief), wie füge ich das jetzt in deine Kursseite ein? Ich verstehe nicht ganz, was mit "HTTPS-Pfad" gemeint ist - einfach nochmal die URL zum Webroot ("https://vads.github.io/MIB4-Softwaredesign/steckbrief")?

**Comment by JirkaDellOro** [comment]
Hallo Bastian,

exakt der!

**Comment by manuel-pross** [comment]
Sehr geehrter @JirkaDellOro 

Bin der Anleitung bis zu dem Teil mit Github Pages gefolgt.  Wenn ich unter Settings -> Github Pages als Source den master branch auswähle wird bei mit folgendes angezeigt:  

Your site is published at https://manuel-pross.github.io/SofDesSS2020/

Allerdings bekomme ich einen 404er.

Diverse stackoverflow-Einträge empfehlen Folgende Vorgehensweisen: 

- empty push (durchgeführt - hat nicht funktioniert)
- ein jekyll theme auswählen (durchgeführt - hat nicht funktioniert)
- https://manuel-pross.github.io/SofDesSS2020/index.html direkt ansprechen (durchgeführt - hat nicht funktioniert)
- STRG + F5 (durchgeführt - hat nicht funktioniert)
- warten (angegeben werden 10 Minuten. Zum Zeitpunkt der Erstellung dieses Beitrags sind es ca 2 Stunden)

Die Ordnerstruktur meines Repositories habe ich mit den Bereits bestehenden der anderen Studenten verglichen und habe keinen Fehler gefunden.

Fällt Ihnen noch etwas ein woran es liegen könnte?

Vielen Dank schon einmal

Grüße Manuel

**Comment by JirkaDellOro** [comment]
Hallo Manuel,

bitte keine Posts löschen. Ich kriege eine Mail und wundere mich dann, dass hier eine Inkonsistenz auftritt. Poste stattdessen dazu, was das Problem und was deine Lösung war, dann können wir vielleicht alle etwas lernen!


--Mit den besten Grüßen
Jirka R. Dell'Oro-FriedlProf. Dipl.-Ing. (FH), 5. Dan
Software & Games | Design & Development
Spiellabor L2.09 | Tel:07723-920-2569
Hochschule Furtwangen University

Am Donnerstag, April 02, 2020 20:38 CEST, schrieb manuel-pross <notifications@github.com>:
 
 
Sehr geehrter @JirkaDellOro
Bin der Anleitung bis zu dem Teil mit Github Pages gefolgt. Wenn ich unter Settings -> Github Pages als Source den master branch auswähle wird bei mit folgendes angezeigt:
Your site is published at https://manuel-pross.github.io/SofDesSS2020/
Allerdings bekomme ich einen 404er.
Diverse stackoverflow-Einträge empfehlen Folgende Vorgehensweisen:
 * empty push (durchgeführt - hat nicht funktioniert) * ein jekyll theme auswählen (durchgeführt - hat nicht funktioniert) * https://manuel-pross.github.io/SofDesSS2020/index.html direkt ansprechen (durchgeführt - hat nicht funktioniert) * STRG + F5 (durchgeführt - hat nicht funktioniert) * warten (angegeben werden 10 Minuten. Zum Zeitpunkt der Erstellung dieses Beitrags sind es ca 2 Stunden)
Die Ordnerstruktur meines Repositories habe ich mit den Bereits bestehenden der anderen Studenten verglichen und habe keinen Fehler gefunden.
Fällt Ihnen noch etwas ein woran es liegen könnte?
Vielen Dank schon einmal
Grüße Manuel

**Comment by manuel-pross** [comment]
Alles klar

Die Seite die über den Link unter Settings -> GitHub Pages im GitHub-Repository erreichbar sein soll ist immer noch nicht da. Allerdings ist es möglich über den Suffix /steckbrief an den Ordner im Repository ranzukommen.

Hoffe das zählt als Lösung.

**Comment by JirkaDellOro** [comment]
Doch, es ist alles da. Pages ist ein einfacher Fileserver, der die die Dateien so heraus gibt, wie sie in der Struktur deines Repositories verortet sind. Da deine Dateien im Ordner "steckbrief" liegen, musst Du diesen in deinem Pfad angeben.
https://manuel-pross.github.io/SofDesSS2020/steckbrief/portrait.jpg
https://manuel-pross.github.io/SofDesSS2020/steckbrief/steckbrief.htm

**Comment by DesiS96** [comment]
Hallo @JirkaDellOro Welcher Ordner ist bei der Registrierung für die Kursseite genau gemeint? Einfach der Link zum Repository? Und wenn ich auf Hausaufgabe 0 im Ordner Steckbrief-Muster gehe finde ich da keine Vorlage für den Steckbrief. Und was genau ist dieses Github-Pages, wo muss ich das aktivieren?

**Comment by JirkaDellOro** [comment]
@DesiS96 : Das sind die richtigen Fragen!

Schau mal in deinem Repository unter Settings, da findest Du Pages. Vielleicht kannst Du dann mit meiner Antwort oben drüber schon alles zusammenbauen. Ansonsten gerne nochmal posten!

**Comment by DesiS96** [comment]
Alles klar, danke
Allerdings kann ich nicht auf das Steckbrief-Muster auf der Kursseite zugreifen. So wie ich das verstanden habe müsste das eine zip-Datei sein? Leider wird mir immer das hier angezeigt wenn ich den Verlinkungen zum Steckbrief-Muster folge:

Not Found
The requested URL /~del/Softwaredesign/Steckbrief/link was not found on this server.

Folge ich der falschen Verlinkung oder ist das ein Fehler der Seite?

**Comment by JirkaDellOro** [comment]
Hier ist es keine Zip-Datei. Per Klick solltest Du direkt auf einen Mustersteckbrief kommen, den Du einfach speichern kannst. Funktioniert das nicht?

**Comment by DesiS96** [comment]
Nein, also es sieht jedenfalls nicht nach einem Steckbrief aus. Wenn ich auf der Kursseite  auf Steckbrief-Muster klicke komme ich auf eine Seite auf der Hausaufgabe0(Datum) steht und wenn ich dann darauf klicke kommt die Meldung dass es das nicht findet.

**Comment by Bassadin** [comment]
Also https://webuser.hs-furtwangen.de/~del/Softwaredesign/Steckbrief/link führt zu nem 404

**Comment by DesiS96** [comment]
Ah ich glaube ich hatte das falsch verstanden. Ich habe jetzt einfach den Link "Steckbrief-Muster" gespeichert und ich nehme mal an dass das jetzt der richtige Steckbrief ist. 
@VADS  Danke trotzdem für die Antwort :)

Bzw. ganz sicher bin ich mir nicht ob das jetzt der richtige Steckbrief ist. Es ist einfach der Link und als ich ihn im Editor geöffnet habe hatte ich den selben html-Code den ich bei Leuten gesehen habe, die bereits abgegeben haben. Anders als in der Mail beschrieben beinhaltet der allerdings kein Portrait das ich durch meins ersetzen könnte.

**Comment by JirkaDellOro** [comment]
Ich lasse euch mal ein bißchen rätseln und helfen, das ist eine sehr gute Übung!

**Comment by JirkaDellOro** [comment]
PS: 

> Wenn ich auf der Kursseite auf Steckbrief-Muster klicke komme ich auf eine Seite auf der Hausaufgabe0(Datum)

Das ist der Steckbrief

**Comment by DesiS96** [comment]
Achso. Danke

**Comment by Bassadin** [comment]
Passt das bei mir soweit auch? Bisher wurde scheinbar nur das Feedbackfeld von Simon aktualisiert?

**Comment by DesiS96** [comment]
Das Portrait kommt aber schon in die html-Datei oder? Wenn ja finde ich nicht raus wo das Alte ist und  damit hab ich die Maße nicht die das neue braucht...

**Comment by JirkaDellOro** [comment]
> Passt das bei mir soweit auch? Bisher wurde scheinbar nur das Feedbackfeld von Simon aktualisiert?

Er war der Erste!

**Comment by JirkaDellOro** [comment]
> Das Portrait kommt aber schon in die html-Datei oder? Wenn ja finde ich nicht raus wo das Alte ist und damit hab ich die Maße nicht die das neue braucht...

Nein, das liegt einfach parallel zum Steckbrief im gleichen Ordner. Der Aggregator sucht sich die beiden Dateien raus und stellt sie dar. Untersuche die Portraits der anderen für das richtige Maß.

**Comment by DesiS96** [comment]
Okay danke für die Antworten. Hat jetzt auch alles geklappt :)

**Comment by SevenChords** [comment]
hallo, bei mir kommt bei der registrierung die fehlermeldung das portrait hat das falsche maß, gefordert sind 85x110 pixel, ich habe nochmal kontrolliert, genau 85x110 pixel groß
<img width="453" alt="Screenshot 2020-04-13 at 14 55 27" src="https://user-images.githubusercontent.com/31819497/79122478-058f4d80-7d98-11ea-9e4a-cae475e0ac78.png">

**Comment by JirkaDellOro** [comment]
Welchen Pfad gibst Du an bei der Registrierung?

**Comment by SevenChords** [comment]
https://github.com/SevenChords/MIB_Softwaredesign/blob/master/
den steckbrief scheint er zu finden, steckbrief und portrait liegen beide im selben verzeichnis, wenn ich https://github.com/SevenChords/MIB_Softwaredesign/blob/master/steckbrief.htm angebe (kopiert aus der url leiste auf github) sagt er er findet den steckbrief nicht, die fehlermeldung kommt bei dem https://github.com/SevenChords/MIB_Softwaredesign/blob/master/ nicht

wenn der pfad das problem ist frage ich mich warum beim einen pfad die fehlermeldung kommt er kann den steckbrief nicht finden und beim anderen dass das bild eine falsche größe hat

**Comment by SevenChords** [comment]
ok, jetzt hat es geklappt, hatte verpeilt den link von github pages zu nehmen statt den von der normalen github seite

**Comment by manuel-pross** [comment]
Hallo @JirkaDellOro 

Wo finde ich die in der Sitzung angesprochenen Dateien: tsconfig.json und tslint.json? 
Sind die im Repo?

**Comment by pKaserr** [comment]
> Hallo @JirkaDellOro
> 
> Wo finde ich die in der Sitzung angesprochenen Dateien: tsconfig.json und tslint.json?
> Sind die im Repo?

Aus der Repo von ihm, wenn er es schon hochgeladen hat.

**Comment by JirkaDellOro** [comment]
ist jetzt da, siehe S20

**Comment by SevenChords** [comment]
woher sollte die main.js.map datei normal herkommen? die wird bei mir irgendwie nicht erzeugt

**Comment by manuel-pross** [comment]
Es gibt in der tsconfig.json eine Property: "sourceMap"
Ist die bei dir auf true?

**Comment by SevenChords** [comment]
ja, ist auf true, auf github pages funktioniert auch alles, nur die .map datei existiert nicht

**Comment by manuel-pross** [comment]
Mit welchem Befehl kompilierst du?
Bei mir wird sie mit "tsc" erzeugt.

Die hat meine ich keinen Einfluss auf die Funktionalität. Die hilft glaub nur beim debuggen des Codes im Browser.

**Comment by SevenChords** [comment]
habe die main.js datei auch per tsc main.ts erzeugt, aber wenn die keinen grossen einfluss hat warte ich damit bis wir dienstag wieder vorlesung beim jirka haben, danke dir.

**Comment by JirkaDellOro** [comment]
es wurde auch kein "use strict" emittiert. Fraglich, ob die tsconfig überhaupt berücksichtigt wurde. In welchem Verzeichnis hast Du tsc gestartet?

Außerdem:
- Nutzt doch die Build-Kommandos von VSCode
- bitte legt für jede Frage einen eigenen Issue an!
