### ISSUE TITLE
"Kompilierte" JS-Dateien hochladen?

### ISSUE THREAD

**Issue by Bassadin** [JirkaDellOro/Softwaredesign#26]
Committet man für gewöhnlich sowohl die .ts als auch die .js-Files oder nur die .ts? Kompilieren kann man ja immer selbst neu . ich kenn das nur von z.B. Java, wo man ja auch die kompilierten Sachen nicht mit pusht oder z.B. der node_modules-Ordner.

**Comment by JirkaDellOro** [comment]
Hallo Bastian,

bitte unbedingt alles pushen! Ich erkläre und demonstriere morgen warum.

**Comment by Bassadin** [comment]
Danke für die Antwort :)
