### ISSUE TITLE
Aufgabe 1-1 

### ISSUE THREAD

**Issue by benediktgrether** [JirkaDellOro/Softwaredesign#3]
Wir haben eine Frage: 
> getCubeInfo(...), welche ebenfalls die Größe entgegen nimmt ...

Welche Größe ist damit gemeint?

- Ist damit die Größe gemeint, die wir bei der Konsolen Eingabe mitliefern,
- Oder meinten Sie den berechneten Werte aus den zwei Methoden
`getCubeSurface(...)` und `getCubeVolume(...)` ?

Über eine Antwort würde ich mich freuen.

**Comment by JirkaDellOro** [comment]
Aus der Aufgabenstellung: Der Nutzer gibt bei Aufruf des Programms in der Kommandozeile einen Buchstaben für den Typ des Körpers an (w, k oder o) sowie die Größe als Kantenlänge bzw. Durchmesser.
