### ISSUE TITLE
NullReferenceException

### ISSUE THREAD

**Issue by katharinaeisenhardt** [JirkaDellOro/Softwaredesign#6]
Unhandled Exception: System.NullReferenceException: Object reference not set to an instance of an object.
   at FinaleAbgabe.GameData.CreateCharacters() in C:\Users\Katharina\Desktop\Softwaredesign\SoftwareDesign\FinaleAbgabe\GameData.cs:line 157

Dieser Buildfehler wird ständig angezeigt, obwohl in dieser Zeile ein neues Objekt vom Typ Avatar erstellt wird:
public static void CreateCharacters()
        {
            Avatar   ForestGodess = new Avatar   //Zeile 157
            (
            "Godess of the forest", 1F, 0.2F, "I'm the Godess of the forest. I'm your Avatar. Our Mission is to free the forest spirits from the tyrannic Deathking!", rooms["Silent Glade"]
            );
}

**Comment by JirkaDellOro** [comment]
Es ist kein Compilezeitfehler, sondern ein Laufzeitfehler. rooms ist noch nicht definiert, wenn ihr versucht die Charaktere zu bauen.
