### ISSUE TITLE
Fragen

### ISSUE THREAD

**Issue by katharinaeisenhardt** [JirkaDellOro/Softwaredesign#7]
Wie übergibt man eine leere Inventoryliste als Eigenschaft eines Objekts vom Typ Character?
Inventory als Dictionary damit nur 1 Itemsliste und nicht Health und Gear Listen einzeln bei Inventory Ausgabe dastehen? https://github.com/katharinaeisenhardt/SoftwareDesign/blob/master/FinaleAbgabe/GameData.cs

Für die Methode Fight():  Es ist nicht möglich auf Enemy.Lifepoints zu zugreifen, nur auf bestimmten Character wegen dem Dictionary.

Navigation: _currentLocation wird richtig ausgegeben aber nicht überschrieben für den Raumwechsel. Startet wieder im Anfangsraum.  -> CheckNonFightCases()
https://github.com/katharinaeisenhardt/SoftwareDesign/blob/master/FinaleAbgabe/MethodStore.cs

**Comment by JirkaDellOro** [comment]
Die Fragen sind leider so schlecht formuliert, dass ich sie nicht verstehe. Bitte pro Frage einen Thread und bitte versuchen, die Fragen verständlich zu formulieren. Fragt euch erst gegenseitig und wenn ihr meint, eine verständliche Formulierung gefunden zu haben, dann postet.
